import type { Metadata } from "next";
import { Inter as FontSans} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import TopMenu from "@/components/custom/TopMenu";
import { ToggleButton } from "@/components/custom/ToggleButton";
import { Toaster } from "@/components/ui/toaster";

const inter = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", inter.variable)}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem >
          <div className="absolute top-10 right-10 flex" >
            <div className="mr-2" >
            <TopMenu />  
            </div>
            <ToggleButton/>
          </div>
        {children}
          <Toaster/>
        </ThemeProvider>
      </body>
    </html>
  );
}
